version: "2"
services:
  httpd:
    build: './httpd/'
    depends_on:
      - memcached
      - mariadb
    networks:
      - frontend
      - backend
    restart: on-failure
    privileged: true
    ports:
      - "10080:10080"
    volumes:
      - /mnt/share/p/Shared/html/:/var/www/html/
    container_name: httpd

  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: sysadmin
    networks:
      - frontend
      - backend
    restart: on-failure
    ports:
      - "3306:3306"
      - "4306:3306" 
      - "5567:5567" 
      - "5444:5444" 
      - "5568:5568"
    volumes:
     - /opt/docker/volumes/mysql:/var/lib/mysql
     - ./mysql/dump:/docker-entrypoint-initdb.d
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: sysadmin
    networks:
      - backend
    depends_on:
      - mariadb
    container_name: phpmyadmin

  memcached:
    image: memcached:1.5.12
    networks:
      - frontend
      - backend
    restart: on-failure
    ports:
      - "11211:11211"
    container_name: memcached

networks:
  frontend:
  backend:

