version: "3.2"
services:
  httpd:
    build: './httpd/'
    depends_on:
      - php
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - frontend
      - backend
    restart: on-failure
    privileged: true
    ports:
      - "80:10080"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /mnt/share/m/Shared/html/:/var/www/html/
    container_name: httpd1

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: sysadmin
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - backend
    restart: on-failure
    ports:
      - "3306:3306"
      - "4306:3306" 
      - "5567:5567" 
      - "5444:5444" 
      - "5568:5568"
    volumes:
     - /var/lib/mysql:/var/lib/mysql
     - ./mysql/dump:/docker-entrypoint-initdb.d
    container_name: mysql1

  memcached:
    image: memcached:1.5.12
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
      - backend
    restart: on-failure
    container_name: memcached1

networks:
  frontend:
  backend:
